name: 'Build Pre-Version'
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/sw_build.yml
    with:
        gitversion-config: './.github/GitVersion.yml'
        push_artifact: true
        
