name: "Pull Request"
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/sw_build.yml
    with:
      gitversion-config: './.github/GitVersion.yml'
      push_artifact: false